[#765] get useradd command consistent, using shortforms, create group explicitly, and no longer delete the unix user during uninstall

diff --git a/packaging/e-irods.list.template b/packaging/e-irods.list.template
--- a/packaging/e-irods.list.template
+++ b/packaging/e-irods.list.template
@@ -55,23 +55,31 @@ $DB_PASS=SOMEPASSWORD
 # =-=-=-=-=-=-=-
 # preinstall directives 
 # =-=-=-=-=-=-=-
-# determine if the service account already exists                                                                       
 %preinstall << END_PREINSTALL
 
-USER=$$( grep $OS_EIRODS_ACCT /etc/passwd )
-if [ -n "$$USER" ]; then                                                                                                 
-	echo "WARNING :: Service Account $OS_EIRODS_ACCT Already Exists."                                                                  
-else                                                                                                                    
-# =-=-=-=-=-=-=-                                                                                                      
+# =-=-=-=-=-=-=-
 # create the service account
-	echo Creating Service Account: $OS_EIRODS_ACCT at $EIRODS_HOME_DIR
-	useradd --system --quiet --home $EIRODS_HOME_DIR --no-create-home \
-	    --shell /bin/bash --group -gecos "E-iRODS administrator" $OS_EIRODS_ACCT
+echo "Creating Service Group and Account: $OS_EIRODS_ACCT at $EIRODS_HOME_DIR"
 
-	ACCT=$OS_EIRODS_ACCT
-	mkdir -p $EIRODS_HOME_DIR
-	chown $$ACCT:$$ACCT $EIRODS_HOME_DIR
+if [[ `getent group $OS_EIRODS_ACCT` != "" ]]; then
+  echo "ERROR :: Please delete the existing Service Group $OS_EIRODS_ACCT before proceeding."
+  if [[ `getent passwd $OS_EIRODS_ACCT` != "" ]]; then
+    echo "      :: The $OS_EIRODS_ACCT Service Account must be deleted prior to deleting the $OS_EIRODS_ACCT Service Group."
+  fi
+  exit 1
+else
+  groupadd -r $OS_EIRODS_ACCT
 fi
+
+if [[ `getent passwd $OS_EIRODS_ACCT` != "" ]]; then
+  echo "ERROR :: Please delete the existing Service Account $OS_EIRODS_ACCT before proceeding."
+  exit 1
+else
+  useradd -r -d $EIRODS_HOME_DIR -M -s /bin/bash -g $OS_EIRODS_ACCT -c "E-iRODS Administrator" $OS_EIRODS_ACCT
+fi
+
+mkdir -p $EIRODS_HOME_DIR
+chown $OS_EIRODS_ACCT:$OS_EIRODS_ACCT $EIRODS_HOME_DIR
 
 END_PREINSTALL
 
